version: '3.8'

services:
  app:
    build: .
    image: my-node-app
    container_name: node_app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=mydatabase
    restart: on-failure

  db:
    image: postgres:14-alpine
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./resources:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: